Feature events private
KossySteve/private-events pull request #3
Opened 2020-10-01 21:06 UTC by mimipeshy

On this milestone we accomplished:
 

- [ ] Created a User model

- [ ]  Created an Event model

 

- [ ] Created a UserEvent model to join both models with many to many associations

 

- [ ] Created sessions for logged in users.

 

- [ ] Organized events according to their date (i.e. past and upcoming events)

- [ ]  Implemented the views for each Model accordingly

2020-10-02 00:54 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Hi, Kossy how are you doing bro, well I can say that you have made an impressive job :clap: :100: :+1:  but you still need to work :hammer: :wrench: more on it to get it approved :checkered_flag: 

## Required Changes:

- [x] Event's index page should display past and upcoming events lists.

- [ ] The event's show page should display the list of attendants.

- [ ] why you are having a home page with a login form? while the user is logged in.

- [ ] please work on the readme don't forget to make a live demo link.

- [ ] don't forget to configure your linter, this step should be done in the beginning.
 
- [ ] remove logic from your views, you should use view helpers `app/helpers/*_helper.rb`

- [ ] models should have unit tests for validations and associations (Rspec):
![image](https://user-images.githubusercontent.com/34653764/94877075-6ba88380-0451-11eb-9a55-186e55b5d1bc.png)

- [ ] authentication should have integration tests (Rspec + Capybara):
![image](https://user-images.githubusercontent.com/34653764/94877098-83800780-0451-11eb-8eb3-9729aaad6ccb.png)

- [ ] event managment features should have integration tests (Rspec + Capybara)

- [ ] I have also left some comments below please check them also.

## Optional Changes:

- [ ] you could use some styling, try to get inspired by this [website](https://github.com/elmejdki/private_events)

- [ ] routes only for used actions, i.e. `resources :events, only: [:new, :create, :show, :index]`

### Please Make all the required changes before you submit another code review.
## Happy Coding :tophat:
_you know how to find me **Kossy** if you need help or something_

2020-10-02 00:54 UTC, elmejdki commented on app/models/event.rb
> +  has_many :attendance, foreign_key: :attended_event_id
I believe the attendance should be plural because of has_many please make sure of that

2020-10-02 00:54 UTC, elmejdki commented on app/models/user.rb
> +  has_many :attendance, foreign_key: :attendee_id
I believe the attendance should be plural because of has_many please make sure of that

2020-10-02 00:54 UTC, elmejdki commented on app/controllers/events_controller.rb
> +    @events = Event.all
as mentioned above the index page of events should show previous and upcoming events separately

2020-10-02 00:54 UTC, elmejdki commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
you can use just `current_user` instead of looking for it.

2020-10-02 00:54 UTC, elmejdki commented on db/migrate/20200930042543_create_attendances.rb
> +      t.belongs_to :attended_event, foreign_key: { to_table: :events }
instead of `attendee` and `attended_event` use `user` and `event`

2020-11-10 02:43 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Excellent Job! 👏 so far team!
Both of you have done well on this project, let's make a few changes, and we will be done.

- [x] Add an index for creator_id column

- [ ] Add an index for both the attendee_id and attended_event_id columns

- [ ] Check the comments I have made on your code. Kindly do make sure you remove all logic from your views.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-10 02:43 UTC, acushlakoncept commented on app/views/attendees/_attendee.html.erb
> +</div>
There should be absolutely NO logic in views. >Views are only for displaying information that becomes available to it from its corresponding controller not generating it. 
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright
* Another great article to guide you, [Rails View Helpers Best Practices Guide](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)

2020-11-10 21:41 UTC, lekegitrepo approved these changes
## Status: Approved :heavy_check_mark:
#### Hi @KossySteve and @mimipeshy :clap: :clap:
#### You have done a good job. This project is Approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

2020-11-10 21:43 UTC, merged